[package]
name = "bitintr"
version = "0.1.10"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
description = "Portable Bit Manipulation Intrinsics."
documentation = "https://gnzlbg.github.io/bitintr"
homepage = "https://gnzlbg.github.io/bitintr"
repository = "https://github.com/gnzlbg/bitintr"
readme = "readme.md"
keywords = ["portable", "bit", "manipulation", "intrinsics"]
license = "MIT"
build = "build.rs"

[build-dependencies]
rustc_version = "0.1.*"
