[package]
name = "bitintr"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
description = "Bit manipulation intrinsics."
documentation = "https://gnzlbg.github.io/bitintr"
homepage = "https://gnzlbg.github.io/bitintr"
repository = "https://github.com/gnzlbg/bitintr"
readme = "readme.md"
keywords = ["bit", "byte", "algorithm", "bitwise", "word", "intrinsics",
            "bit manipulation"]
license = "MIT"

[dependencies]
clippy = {version = "0.0.80", optional = true}
